//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/sneakyanimeow/RiderProjects/AntlrTests/MyTinyC/MyTinyC.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrTests.MyTinyC {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MyTinyCParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IMyTinyCListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] MyTinyCParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] MyTinyCParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MyTinyCParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MyTinyCParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.paren_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParen_expr([NotNull] MyTinyCParser.Paren_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.paren_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParen_expr([NotNull] MyTinyCParser.Paren_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] MyTinyCParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] MyTinyCParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest([NotNull] MyTinyCParser.TestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest([NotNull] MyTinyCParser.TestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.sum_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSum_([NotNull] MyTinyCParser.Sum_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.sum_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSum_([NotNull] MyTinyCParser.Sum_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] MyTinyCParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] MyTinyCParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.id_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId_([NotNull] MyTinyCParser.Id_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.id_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId_([NotNull] MyTinyCParser.Id_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] MyTinyCParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] MyTinyCParser.IntegerContext context);
}
} // namespace AntlrTests.MyTinyC
