//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/sneakyanimeow/RiderProjects/AntlrTests/MyTinyC/MyTinyC.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrTests.MyTinyC {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMyTinyCListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MyTinyCBaseListener : IMyTinyCListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] MyTinyCParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] MyTinyCParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] MyTinyCParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] MyTinyCParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.paren_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParen_expr([NotNull] MyTinyCParser.Paren_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.paren_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParen_expr([NotNull] MyTinyCParser.Paren_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] MyTinyCParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] MyTinyCParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTest([NotNull] MyTinyCParser.TestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTest([NotNull] MyTinyCParser.TestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.sum_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSum_([NotNull] MyTinyCParser.Sum_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.sum_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSum_([NotNull] MyTinyCParser.Sum_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] MyTinyCParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] MyTinyCParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.id_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId_([NotNull] MyTinyCParser.Id_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.id_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId_([NotNull] MyTinyCParser.Id_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MyTinyCParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] MyTinyCParser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MyTinyCParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] MyTinyCParser.IntegerContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace AntlrTests.MyTinyC
