//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/sneakyanimeow/RiderProjects/AntlrTests/OwOLang/OwOLang.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrTests.OwOLang {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IOwOLangListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class OwOLangBaseListener : IOwOLangListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScript([NotNull] OwOLangParser.ScriptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.script"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScript([NotNull] OwOLangParser.ScriptContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] OwOLangParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] OwOLangParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrint([NotNull] OwOLangParser.PrintContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.print"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrint([NotNull] OwOLangParser.PrintContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.loop_x_times"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoop_x_times([NotNull] OwOLangParser.Loop_x_timesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.loop_x_times"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoop_x_times([NotNull] OwOLangParser.Loop_x_timesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.declare_new_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclare_new_type([NotNull] OwOLangParser.Declare_new_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.declare_new_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclare_new_type([NotNull] OwOLangParser.Declare_new_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.declare_new_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclare_new_variable([NotNull] OwOLangParser.Declare_new_variableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.declare_new_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclare_new_variable([NotNull] OwOLangParser.Declare_new_variableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.set_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSet_variable([NotNull] OwOLangParser.Set_variableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.set_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSet_variable([NotNull] OwOLangParser.Set_variableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.declare_and_set_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclare_and_set_variable([NotNull] OwOLangParser.Declare_and_set_variableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.declare_and_set_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclare_and_set_variable([NotNull] OwOLangParser.Declare_and_set_variableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] OwOLangParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] OwOLangParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] OwOLangParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] OwOLangParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.primitives"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitives([NotNull] OwOLangParser.PrimitivesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.primitives"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitives([NotNull] OwOLangParser.PrimitivesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId([NotNull] OwOLangParser.IdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId([NotNull] OwOLangParser.IdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInt([NotNull] OwOLangParser.IntContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.int"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInt([NotNull] OwOLangParser.IntContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.float"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloat([NotNull] OwOLangParser.FloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.float"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloat([NotNull] OwOLangParser.FloatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] OwOLangParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] OwOLangParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="OwOLangParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool([NotNull] OwOLangParser.BoolContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="OwOLangParser.bool"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool([NotNull] OwOLangParser.BoolContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace AntlrTests.OwOLang
