//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/sneakyanimeow/RiderProjects/AntlrTests/OwOLang/OwOLang.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrTests.OwOLang {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="OwOLangParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IOwOLangVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] OwOLangParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] OwOLangParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.print"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrint([NotNull] OwOLangParser.PrintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.loop_x_times"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoop_x_times([NotNull] OwOLangParser.Loop_x_timesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.declare_new_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare_new_type([NotNull] OwOLangParser.Declare_new_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.declare_new_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare_new_variable([NotNull] OwOLangParser.Declare_new_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.set_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSet_variable([NotNull] OwOLangParser.Set_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.declare_and_set_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclare_and_set_variable([NotNull] OwOLangParser.Declare_and_set_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] OwOLangParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] OwOLangParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.primitives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimitives([NotNull] OwOLangParser.PrimitivesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] OwOLangParser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.int"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInt([NotNull] OwOLangParser.IntContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.float"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloat([NotNull] OwOLangParser.FloatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] OwOLangParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="OwOLangParser.bool"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBool([NotNull] OwOLangParser.BoolContext context);
}
} // namespace AntlrTests.OwOLang
