//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/sneakyanimeow/RiderProjects/AntlrTests/TinyC/TinyC.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrTests.TinyC {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="TinyCParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface ITinyCListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] TinyCParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] TinyCParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] TinyCParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] TinyCParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.paren_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParen_expr([NotNull] TinyCParser.Paren_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.paren_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParen_expr([NotNull] TinyCParser.Paren_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] TinyCParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] TinyCParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTest([NotNull] TinyCParser.TestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.test"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTest([NotNull] TinyCParser.TestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.sum_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSum_([NotNull] TinyCParser.Sum_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.sum_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSum_([NotNull] TinyCParser.Sum_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] TinyCParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] TinyCParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.id_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId_([NotNull] TinyCParser.Id_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.id_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId_([NotNull] TinyCParser.Id_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger([NotNull] TinyCParser.IntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger([NotNull] TinyCParser.IntegerContext context);
}
} // namespace AntlrTests.TinyC
