//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/sneakyanimeow/RiderProjects/AntlrTests/TinyC/TinyC.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AntlrTests.TinyC {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITinyCListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class TinyCBaseListener : ITinyCListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] TinyCParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] TinyCParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] TinyCParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] TinyCParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.paren_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParen_expr([NotNull] TinyCParser.Paren_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.paren_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParen_expr([NotNull] TinyCParser.Paren_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] TinyCParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] TinyCParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTest([NotNull] TinyCParser.TestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTest([NotNull] TinyCParser.TestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.sum_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSum_([NotNull] TinyCParser.Sum_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.sum_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSum_([NotNull] TinyCParser.Sum_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] TinyCParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] TinyCParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.id_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId_([NotNull] TinyCParser.Id_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.id_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId_([NotNull] TinyCParser.Id_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="TinyCParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger([NotNull] TinyCParser.IntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TinyCParser.integer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger([NotNull] TinyCParser.IntegerContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace AntlrTests.TinyC
